name: "Container Action using github-stats-pages"
description: "Retrieve github stats and push static content"
author: "Chun Ly"
inputs:
  username:
    description: "GitHub username or organization name"
    required: true
  token:
    description: "GitHub Personal Access Token"
    required: true
  test:
    description: "For CI testing. Runs a subset of repositories"
    required: false
    default: ''
  include-repos:
    description: "List of repositories to only include for static pages. Comma-separated list"
    required: false
    default: ''
  exclude-repos:
    description: "List of repositories to exclude from public list of repositories. Comma-separated list"
    required: false
    default: ''
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.username }}
    - ${{ inputs.token }}
    - ${{ inputs.test }}
    - ${{ inputs.include-repos }}
    - ${{ inputs.exclude-repos }}
